# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: PR checks
on: 
  push:
    branches-ignore: [main]
jobs:
  build:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Read from .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Read node version
        run: node -v

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test:nowatch

      - name: Build project
        run: yarn build
