# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Node.js CI

on:
  push:
    branches-ignore: main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: dcodeIO/setup-node-nvm@master
        with:
          cmd: nvm install
          cmd: nvm use
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:nowatch
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build