# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: PR checks
on: 
  push:
    branches-ignore: [main]
jobs:
  build:
    name: PR Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Read from .nvmrc
        id: from_nvmrc
        run: echo ::set-output name=node_version::$(cat .nvmrc)
        shell: bash

      - name: Setup Node.js version ${{ steps.from_nvmrc.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.from_nvmrc.outputs.node_version }}

      - name: Read node version
        run: node -v

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test:nowatch

      - name: Build project
        run: yarn build
